/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 鏈嶅姟绔笅鍙戠殑 prompt 娑堟伅 */
export interface PromptMessage {
  /** 瑙勮寖 搂4.1锛氭秷鎭€氫俊妯″紡 鈥?request | response | notification */
  envelop_type?: string
  msg_id: string
  guid?: string
  user_id?: string
  method: string
  payload: PromptPayload
  /** 瑙勮寖 搂4.1锛氭墿灞曞瓧娈碉紝鍖呭惈 trace_id / channel 绛?*/
  extra?: Record<string, string>
}
/** 鏈嶅姟绔笅鍙戠殑 cancel 娑堟伅 */
export interface CancelMessage {
  envelop_type?: string
  msg_id: string
  guid?: string
  user_id?: string
  method: string
  payload: CancelPayload
  extra?: Record<string, string>
}
/**
 * 鏈嶅姟绔笅鍙戠殑 kickout 閫氱煡锛堣鑼?搂7.2锛? *
 * 瀹㈡埛绔敹鍒板悗锛? * 1. agp-native 浼氭牴鎹?delay_ms + random_ms 璋冩暣涓嬫 reconnect 绛夊緟
 * 2. JS 灞傛敹鍒?onKickout 鍥炶皟锛屽彲鎹鎻愮ず鐢ㄦ埛鎴栨竻鐞嗕笟鍔＄姸鎬? *
 * 娉ㄦ剰锛歬ickout 涔嬪悗鍚庣閫氬父浼氶殢鍗冲彂 Close(4503)锛岀湡姝ｇ殑鏂繛/閲嶈繛璧? * onDisconnected 璺緞锛屾湰鍥炶皟浠呬綔涓?鎻愬墠閫氱煡"銆? *
 * 瀛楁瀵瑰簲鍚庣 wire 鏍煎紡锛堝弬瑙?`docs/socket-backend-harden.md` 搂7.2锛夛細
 *   delay_ms  鈫愨啋  delayMs  (camelCase)
 *   random_ms 鈫愨啋  randomMs
 *   server_time 鈫愨啋 serverTime
 */
export interface KickoutInfo {
  reason?: string
  delay_ms?: number
  random_ms?: number
  server_time?: number
}
export interface PromptPayload {
  session_id: string
  prompt_id: string
  agent_app: string
  content: Array<ContentBlock>
  /** 鏈嶅姟绔寚瀹氱殑 Agent ID锛堝皬绋嬪簭/APP 鍦烘櫙锛夛紝鍙€?*/
  agent_id?: string
  /** 娓犻亾鏍囪瘑锛坵xkf / miniapp / web / app锛夛紝鍙€?*/
  channel?: string
}
export interface CancelPayload {
  session_id: string
  prompt_id: string
  agent_app: string
}
/** 鍐呭鍧?*/
export interface ContentBlock {
  type: string
  text: string
}
/** 宸ュ叿璋冪敤淇℃伅 */
export interface ToolCall {
  tool_call_id: string
  title?: string
  kind?: string
  status: string
  content?: Array<ContentBlock>
  locations?: Array<ToolLocation>
}
export interface ToolLocation {
  path: string
}
/** 鏈€缁堝搷搴?payload */
export interface PromptResponsePayload {
  session_id: string
  prompt_id: string
  stop_reason: string
  content?: Array<ContentBlock>
  error?: string
  /**
   * 瑙勮寖 搂4.5 `4xxx 瀹㈡埛绔眰` 閿欒鐮侊紙涓婅鏂瑰悜锛夛細
   * 4001 璇锋眰鍙傛暟閿欒 / 4002 鐗堟湰杩囦綆 / 4003 鍗忚涓嶅吋瀹?绛夈€?   * 鐢卞鎴风涓氬姟灞傚～鍏ワ紝鍚庣鎹鍋氶敊璇垎绫荤粺璁°€?   */
  error_code?: number
  /** 鍥炰紶缁欐湇鍔＄鐨?session key锛堝皬绋嬪簭/APP 鍦烘櫙锛?*/
  session_key?: string
  /** 娑堟伅绫诲瀷锛堝 cron_job 琛ㄧず瀹氭椂浠诲姟瑙﹀彂锛?*/
  msg_type?: string
}
/** WebSocket 瀹㈡埛绔厤缃?*/
export interface WebSocketClientConfig {
  url: string
  guid: string
  user_id: string
  token?: string
  qclaw_version?: string
  reconnect_interval?: number
  max_reconnect_attempts?: number
  heartbeat_interval?: number
  gateway_port?: string
  dedup_capacity?: number
}
/** 杩炴帴鐘舵€?*/
export const enum ConnectionState {
  Disconnected = 'Disconnected',
  Connecting = 'Connecting',
  Connected = 'Connected',
  Reconnecting = 'Reconnecting'
}
/**
 * 缁撴瀯鍖栭敊璇俊鎭紙onError 鍥炶皟鍙傛暟锛? *
 * 鐢ㄤ簬鏇夸唬鏃х増 `onError(err, string)` 鐨勫瓧绗︿覆锛屾妸 tungstenite::Error銆? * HTTP 鎻℃墜澶辫触銆丆lose frame銆佸績璺宠秴鏃剁瓑鍚勭被閿欒浠ョ粨鏋勫寲褰㈠紡閫忓嚭鍒?JS 灞傦紝
 * 渚夸簬璋冪敤鏂规寜 code/kind/retryable 鍋氬垎妗朵笂鎶ュ拰閲嶈繛鍒ゆ柇銆? *
 * - `code`锛氳嚜瀹氫箟閿欒鐮侊紙JS 渚х粺璁＄敤锛屼笌鍚庣 Close Code 涓嶅悓浣撶郴锛? * - `message`锛氫汉鍙閿欒娑堟伅
 * - `kind`锛氶敊璇垎绫伙紝鍙栧€艰 client.rs 涓?categorize_* 鍑芥暟銆? *   涓庤鑼?搂8.2 `reason` 缁村害瀛楀吀淇濇寔涓€鑷达細
 *   杩炴帴闃舵: "transport" | "tls" | "http_handshake" | "protocol" | "auth_failed"
 *   Close frame: "client_close" | "eof" | "kicked" | "pong_timeout" | "maintenance" | "close_frame"
 *   杩愯鏃?    "heartbeat" | "ready_timeout" | "not_ready" | "local" | "unknown"
 * - `retryable`锛氭槸鍚﹀缓璁噸璇曪紙Rust 灞?connection_loop 浼氭嵁姝ょ煭璺級
 * - `http_status`锛欻TTP 鐘舵€佺爜锛屼粎褰?kind="http_handshake" 鎴?"auth_failed" 鏃舵湁鍊? * - `close_code`锛歐ebSocket Close Code锛屼粎褰撴潵婧愪簬 Close frame 鏃舵湁鍊? */
export interface WsErrorInfo {
  code: number
  message: string
  kind: string
  retryable: boolean
  http_status?: number
  close_code?: number
}
/**
 * 鏂繛淇℃伅锛坥nDisconnected 鍥炶皟鍙傛暟锛? *
 * 鐢ㄤ簬鏇夸唬鏃х増 `onDisconnected(err, string)` 鐨勪腑鏂囧瓧绗︿覆鍘熷洜銆? *
 * - `reason`锛氭柇杩炲師鍥犳枃妗? * - `code`锛氫笌 WsErrorInfo.code 鍚屼綋绯荤殑鑷畾涔夐敊璇爜
 * - `is_user_initiated`锛氭槸鍚︾敱鐢ㄦ埛璋冪敤 stop() 涓诲姩鏂紑
 * - `retryable`锛氭槸鍚﹀缓璁噸璇? * - `close_code`锛氭湇鍔＄涓诲姩 Close 鏃剁殑 WebSocket Close Code
 */
export interface WsDisconnectInfo {
  reason: string
  code: number
  is_user_initiated: boolean
  retryable: boolean
  close_code?: number
}
export declare class AgpWebSocketClient {
  constructor(config: WebSocketClientConfig)
  setCallbacks(callbacks: { onConnected?: (err: Error | null) => void; onDisconnected?: (err: Error | null, info: WsDisconnectInfo) => void; onPrompt?: (err: Error | null, message: PromptMessage) => void; onCancel?: (err: Error | null, message: CancelMessage) => void; onError?: (err: Error | null, info: WsErrorInfo) => void; onKickout?: (err: Error | null, info: KickoutInfo) => void; }): void
  start(): void
  stop(): void
  getState(): ConnectionState
  sendMessageChunk(sessionId: string, promptId: string, content: ContentBlock, guid?: string | undefined | null, userId?: string | undefined | null, state?: string | undefined | null, extra?: Record<string, string> | undefined | null): void
  sendToolCall(sessionId: string, promptId: string, toolCall: ToolCall, guid?: string | undefined | null, userId?: string | undefined | null, state?: string | undefined | null, extra?: Record<string, string> | undefined | null): void
  sendToolCallUpdate(sessionId: string, promptId: string, toolCall: ToolCall, guid?: string | undefined | null, userId?: string | undefined | null, state?: string | undefined | null, extra?: Record<string, string> | undefined | null): void
  sendPromptResponse(payload: PromptResponsePayload, guid?: string | undefined | null, userId?: string | undefined | null, extra?: Record<string, string> | undefined | null): void
}
